### ISSUE TITLE
使用时会对所有方式进行加密解密这样就会导致报错而无法使用

### ISSUE THREAD

**Issue by guogegod** [dreamncn/CustomCrypto#2]
如题

**Comment by dreamncn** [comment]
已经关注到这个问题，近期正在重构中。
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/37787014/191710720-de936716-3dfe-419c-bc76-ab8848d6ee5f.png">

**Comment by guogegod** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月22日(星期四) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dreamncn/CustomCrypto] 使用时会对所有方式进行加密解密这样就会导致报错而无法使用 (Issue #2)





 
已经关注到这个问题，近期正在重构中。

**Comment by dreamncn** [comment]
[0.0.3版本](https://github.com/dreamncn/CustomCrypto/releases/tag/0.0.3)已发布，欢迎试用。
